### PR TITLE
Decrypt message

### PR DESCRIPTION
**Pull request by logvik**
we need it for MetaMask/metamask-extension#1190

### CODE REVIEW

**Comment by logvik** [comment]
@lazaridiscom I have tried to do as you said in the previous PR, delete and prepare solid commit and got fail. It shows ok on my localhost, but github track all commits, I can't erase history here. Please stick to files and don't look at commit count or please give me a link on review how should I do that you have asked to do. Thank you in advance.

**Comment by lazaridiscom** [comment]
> I can't erase history here.

you can, it's standard git functionality:

https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History

or some far more compact instructions for your case:

https://blog.liplex.de/how-to-squash-already-pushed-commits/

-

note that if you're not familiar with this, you can mess things up quickly and loose many time.

you can always get a fresh clone from the original repo, and force push it (git push --force) to your fork, then apply your changes again and do the PR.

(Note that all this is not your fault. Git/Github workflow are a showcase for a terrible dev-experience which stayed nearly as-is for years)

**Comment by logvik** [comment]
To erase history on github has to needed delete repo and recreate. Thank you for advice.

**Comment by lazaridiscom** [comment]
You're welcome.

**Comment by lazaridiscom** [comment]
> To erase history on github has to needed delete repo and recreate. Thank you for advice.

note that you NEVER delete the repo (fork) on github. Just locally.

**Pull request closed without merging**
